import AuthProvider from "@/providers/AuthProvider";
import "./globals.css";
import { Open_Sans } from "next/font/google";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full h-[100vh]">
        <AuthProvider>
          <Header />
          <main className="w-full h-[80%] mt-4 flex flex-col items-center">
            {children}
          </main>
        </AuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
